### ISSUE TITLE
Page failed to load upcoming break data.

### ISSUE THREAD

**Issue by FrozenDude101** [georgejkaye/cookiebreaks#105]
![image](https://github.com/georgejkaye/cookiebreaks/assets/69700997/7db03688-df2a-4306-b1aa-c4659d33c3e3)

**Comment by georgejkaye** [comment]
Yeah, noticed this, don't know why it's happening

**Comment by georgejkaye** [comment]
The bug was due to only one argument being passed to a two argument function passed to `map`; the fact that this was permitted to pass the typechecker makes me very sad
