### ISSUE TITLE
Timezone shenanigans

### ISSUE THREAD

**Issue by FrozenDude101** [georgejkaye/cookiebreaks#108]
It's no longer BST, and the clocks moved forwards.
Seems the cookie break times have as well.
The site says they are at 15:30 instead of 14:30.

**Comment by georgejkaye** [comment]
Who could have seen this one coming, I thought I was setting timezones to `Europe/London` somewhere but clearly not in the right places...

**Comment by FrozenDude101** [comment]
I think is related to you trying to fix this, but now there are more cookie breaks. (Or maybe we're just doing 2 hour long breaks 🤔)
![image](https://github.com/georgejkaye/cookiebreaks/assets/69700997/52246b5d-09a1-452d-b04d-95b2f7bb8b0a)
