### ISSUE TITLE
No breaks shown

### ISSUE THREAD

**Issue by FrozenDude101** [georgejkaye/cookiebreaks#110]
![image](https://github.com/georgejkaye/cookiebreaks/assets/69700997/0dd46b95-8927-4f47-8a91-33237ab6ecf3)
Can't believe cookie break's been cancelled 😔

**Comment by FrozenDude101** [comment]
No console errors, but it does print two empty lists and undefined.

**Comment by FrozenDude101** [comment]
oop, 500 error appeared after a few seconds

**Comment by georgejkaye** [comment]
Where have they gone

**Comment by georgejkaye** [comment]
Wait this might be because `georgejkaye.com` now points at a server that I haven't set up cookiebreaks on yet

**Comment by georgejkaye** [comment]
Should be working again now (the certificate will take a little bit to come through so there'll be a security risk but otherwise it's fine)

**Comment by georgejkaye** [comment]
Certificate has propagated, closing
