### ISSUE TITLE
Mooooom it's happening again

### ISSUE THREAD

**Issue by FrozenDude101** [georgejkaye/cookiebreaks#111]
![image](https://github.com/georgejkaye/cookiebreaks/assets/69700997/cb09dbd0-0154-407a-b3c6-ffe18bad25b4)

**Comment by georgejkaye** [comment]
Is this an off by one error about Wednesday vs Thursday

**Comment by FrozenDude101** [comment]
idk, but there's not cookie breaks on tuesdays

**Comment by georgejkaye** [comment]
I've changed the environment variable to be 3, let's see what happens

**Comment by FrozenDude101** [comment]
a lovely debugging method

**Comment by georgejkaye** [comment]
Looks like I finally fixed it, a combination of calculating the day wrong and not updating the prod database to include the uniqueness constraint
