### ISSUE TITLE
Add a notice when a cookie break is on a strike day.

### ISSUE THREAD

**Issue by FrozenDude101** [georgejkaye/cookiebreaks#15]
The 27th is a strike day, and so the cookie break won't be happening.
Instead of `Host Required`, it could say something like `Strike Day`, or other warning mentioning the strikes.
If combined with a way to claim a cookie break, it shouldn't allow someone to try to host on that day.

**Comment by georgejkaye** [comment]
Excellent idea, thank you!

**Comment by georgejkaye** [comment]
Now deployed
